using GodhomeWinLossTracker.Utils;

namespace GodhomeWinLossTracker.MessageBus.Messages
{
    public class RawWinLoss : IMessage
    {
        public RawWinLoss(string timestamp, string sequenceName, string bossName, string sceneName, int wins, int losses, int heals, int healAmount, int hits, int hitAmount, float bossHP, long fightLengthMs, RecordSources recordSource, int bossPhase)
        {
            DevUtils.Assert(timestamp!= null, "timestamp shouldn't be null");
            DevUtils.Assert(sequenceName != null, "sequenceName shouldn't be null");
            DevUtils.Assert(bossName != null, "bossName shouldn't be null");
            DevUtils.Assert(sceneName != null, "sceneName shouldn't be null");

            Timestamp = timestamp;
            SequenceName = sequenceName;
            BossName = bossName;
            SceneName = sceneName;
            Wins = wins;
            Losses = losses;
            Heals = heals;
            HealAmount = healAmount;
            Hits = hits;
            HitAmount = hitAmount;
            BossHP = bossHP;
            FightLengthMs = fightLengthMs;
            RecordSource = recordSource;
            BossPhase = bossPhase;
        }

        public override string ToString()
        {
            DevUtils.Assert(RecordSource == RecordSources.Mod || RecordSource == RecordSources.Test, "Only records generated by mod can be displayed");
            DevUtils.Assert((Wins == 1 && Losses == 0) || (Wins == 0 && Losses == 1), "Records generated by mod should only have one win or one loss");
            string verb = Wins == 1 ? "Won against" : "Lost to";
            string msg = (Losses == 1 && BossPhase != 0) ? $"{verb} {BossName} phase {BossPhase} in {SequenceName}" : $"{verb} {BossName} in {SequenceName}";
            return msg;
        }

        public string Timestamp { get; private set; }
        public string SequenceName { get; private set; }
        public string BossName { get; private set; }
        public string SceneName { get; private set; }
        public int Wins { get; private set; }
        public int Losses { get; private set; }
        public int Heals { get; private set; }
        public int HealAmount { get; private set; }
        public int Hits { get; private set; }
        public int HitAmount { get; private set; }
        public float BossHP { get; private set; }
        public long FightLengthMs { get; private set; }
        public RecordSources RecordSource { get; private set; }
        public int BossPhase { get; private set; }
    }
}
